### ISSUE TITLE
aarch64 package out of date

### ISSUE THREAD

**Issue by hfiguiere** [flathub/com.jgraph.drawio.desktop#47]
Any reason why? I mean any reason you no longer build from source?

**Comment by davidjgraph** [comment]
We are not the authors of that package, we have no knowledge of it.

**Comment by ghisvail** [comment]
> Any reason why?

The current Flatpak manifest performs a repacking of the official DEB package published upstream.

> any reason you no longer build from source?

Buildling from source used to work, but one day it stopped. Investigating further requires time that I don't have currently.

Building Electron apps from source with Flatpak is notoriously hit-and-miss, mainly due to the requirements for supporting offline builds and maintaining lock files properly. Feel free to have a go at it and I'll happily review your PR @hfiguiere

**Comment by ghisvail** [comment]
Alright, drawio is built from source again @hfiguiere :+1: 

Please have a go at the aarch64 release and let me know whether it works.

**Comment by hfiguiere** [comment]
works great ! thanks!
